package com.wuyou.merchant.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wuyou.merchant.bean.UserInfo;
import com.wuyou.merchant.data.local.db.EosAccount;

import com.wuyou.merchant.bean.UserInfoDao;
import com.wuyou.merchant.data.local.db.EosAccountDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userInfoDaoConfig;
    private final DaoConfig eosAccountDaoConfig;

    private final UserInfoDao userInfoDao;
    private final EosAccountDao eosAccountDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        eosAccountDaoConfig = daoConfigMap.get(EosAccountDao.class).clone();
        eosAccountDaoConfig.initIdentityScope(type);

        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);
        eosAccountDao = new EosAccountDao(eosAccountDaoConfig, this);

        registerDao(UserInfo.class, userInfoDao);
        registerDao(EosAccount.class, eosAccountDao);
    }
    
    public void clear() {
        userInfoDaoConfig.clearIdentityScope();
        eosAccountDaoConfig.clearIdentityScope();
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

    public EosAccountDao getEosAccountDao() {
        return eosAccountDao;
    }

}
